spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=validate

spring.cache.type=redis
spring.cache.redis.cache-names=users,usersWithBirthdayToday,expiredCards
spring.cache.redis.time-to-live=600000
spring.cache.redis.specific.usersWithBirthdayToday.time-to-live=3600000
spring.cache.redis.specific.expiredCards.time-to-live=3600000

jwt.access.secret=${JWT_ACCESS_SECRET}

spring.mvc.problemdetails.enabled=true

application.config.auth-url=${AUTH_SERVICE_URL}

management.endpoints.web.exposure.include=health,metrics,prometheus
management.tracing.sampling.probability=1.0
#todo: check that ports compatible with docker-compose ports
management.otlp.tracing.endpoint=http://tempo:4318/v1/traces 

#check if I need to define a log-pattern here if I have one in logback.xml
